//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    using DatabaseModel.Core;
    
    public partial class Autor : IBaseClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autor()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        public string PrimeiroNome { get; set; }
        public string MeioNome { get; set; }
        public string UltimoNome { get; set; }
        public string PenName { get; set; }
        public string Email { get; set; }
        public string Twitter { get; set; }
        public string Biografia { get; set; }
        public string BiografiaResumida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
    }
}
